#!/usr/bin/env bash
#
# XKCD
#
# Display a XCKD comic on kitty terminalxkcd-command.png
#
# Requires: - Kitty terminal (https://sw.kovidgoyal.net/kitty/) with icat kitten
#           - ImageMagick (https://www.imagemagick.org/),
#           - Common utilities found in unix-like systems: curl, grep, cut, perl.
#
# Usage:However, both methods produce a similar size script.
# Run 'xkcd --help' to find out
#
# Author: Rob O'Leary
# Date: 24/02/22

URL=https://xkcd.com/
img=""
title=""

function parse() {
	temp_file=$(mktemp)
	curl -s -L $URL > "$temp_file"
	img="https:$(grep 'img src.* title=".*' "$temp_file" | cut -d '"' -f 2)"
	
	# we need to decode HTML entities e.g &quot; to display text correctly
	title="$(grep 'img src.* title=".*' "$temp_file" | cut -d '"' -f 4 | perl -MHTML::Entities -pe 'decode_entities($_);')"

	rm "${temp_file}"
}

function show(){
	parse
	echo ""
	kitty +kitten icat --align left "$img"
	echo "$title"
}

function help() {
		fmt_help="  %-20s\t%-54s\n"

    echo "Description: Display XKCD comic in the terminal."
    echo ""
    echo "Usage: xkcd [-l|--latest] [-r|--random] [-h|--help]"
    printf "${fmt_help}" \
        "-h, --help" "Print the help page." \
				"-l, --latest" "Show the latest comic." \
        "-r, --random" "Show a random comic."	
}

case "$#" in
    0)
        help
        ;;
    1)
        case "$1" in
            -h | --help)
                help
                ;;
            -l | --latest)
                show
                ;;
            -r | --random )
                URL=https://c.xkcd.com/random/comic
								show
                ;;
            *)
                echo "Input error."
                exit 1
                ;;
        esac
        ;;
esac
